export { Player } from './main/contestants/player'
export { Team } from './main/contestants/team'
export { Duel } from './main/matches/duel'
export { FreeForAll } from './main/matches/free-for-all'
export { TeamDuel } from './main/matches/team-duel'
export { TeamFreeForAll } from './main/matches/team-free-for-all'
export type { PlayerResult, TeamResult, Results } from './lib/match/results'
export { MatchError, ErrorType } from './lib/match/error'
