name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Create build
        run: pnpm build
      - name: Run lint
        run: pnpm lint
      - name: Run format check
        run: pnpm format --check
      - name: Run tests
        run: pnpm test
